### ISSUE TITLE
is there a way to pass flags to the test command

### ISSUE THREAD

**Issue by 0xbok** [MorenaBarboni/SuMo-SOlidity-MUtator#11]
thanks for this tool to make mutation testing easier. I'm trying this out on a repo which uses this command to run tests:
`forge test --ffi`

Is there a way to pass these extra flags via `sumo-config.js` or `npx sumo`?

**Comment by MorenaBarboni** [comment]
Hi there, yes there is a way to override the default test script. In the `sumo-config.js`  you can set "custom" as your testing framework. In this way, SuMo will use the `compile` and `test`  scripts defined in your `package.json` for testing. So you can edit those scripts specifying all the flags you need. I hope this helps!
