### ISSUE TITLE
This repository is missing a license

### ISSUE THREAD

**Issue by cyrille-artho** [MorenaBarboni/SuMo-SOlidity-MUtator#6]
Dear authors,
Your tool looks really interesting, but please be aware that without a license, your code is protected by copyright and cannot be safely used by others. Consider adding an open-source license to your repository (as that seems to be your intent) so others know under what conditions they are allowed to use your code.
Make sure all authors who have contributed so far agree to that license.
Good luck!

**Comment by MorenaBarboni** [comment]
Solved this in 772a00c
